### ISSUE TITLE
Cartopy build fails

### ISSUE THREAD

**Issue by AlexReedy** [radical-collaboration/PaleoSTeHM#18]
Issue with Cartopy unable to determine GEOS version due to it being unable to identify GEOS version. Cartopy requires external system libraries 

`sudo apt -y install libgeos-dev`

Which can't be done on amarel as it requires admin privileges to sudo. Need to find work around or another package that works equivalently to Cartopy.

**Comment by yc-lin-geo** [comment]
I think a possible solution is to use conda to set a virtual enviroment instead of venv?

**Comment by bobkopp** [comment]
Yes, worth trying
________________________________

**Comment by yc-lin-geo** [comment]
I tried install virtual environment with conda, it works in my computer now. I created a pull requst for that, hope this works!

**Comment by yc-lin-geo** [comment]
This issue is solved by using conda to build the environment.
